### ISSUE TITLE
Install with Python 3.11 fails

### ISSUE THREAD

**Issue by olivhoenen** [cherab/imas#2] opened 2024-07-08 16:02 UTC
As part of the move to RHEL9 based system for ITER's SDCC, I've tried to install `cherab.imas` with Python 3.11. It complained with the following cython-related error:
```
      running build_ext
      building 'cherab.imas.math.functions.vector_functions' extension
      gcc -DNDEBUG -g -fwrapv -O3 -Wall -O2 -ftree-vectorize -march=sandybridge -fno-math-errno -fPIC -O2 -ftree-vectorize -march=sandybridge -fno-math-errno -fPIC -fPIC -I. -I/tmp/pip-build-env-iptcz_k7/overlay/lib/python3.11/site-packages/numpy/core/include -I/work/imas/opt/EasyBuild/software/Python/3.11.5-GCCcore-13.2.0/include/python3.11 -c cherab/imas/math/functions/vector_functions.c -o build/temp.linux-x86_64-cpython-311/cherab/imas/math/functions/vector_functions.o
      cherab/imas/math/functions/vector_functions.c:296:12: fatal error: longintrepr.h: No such file or directory
        296 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/work/imas/opt/EasyBuild/software/GCCcore/13.2.0/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cherab-imas
Failed to build cherab-imas
ERROR: Could not build wheels for cherab-imas, which is required to install pyproject.toml-based projects
```

It seems like avoiding a pre-release cython3 helps, e.g. with the following patch to `pyproject.toml`:
```
$ git diff pyproject.toml
diff --git a/pyproject.toml b/pyproject.toml
index 5444a93..39f8695 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,3 +1,3 @@
 [build-system]
-requires = ["setuptools", "wheel", "oldest-supported-numpy", "cython==3.0a5", "raysect==0.7.1", "cherab==1.4"]
+requires = ["setuptools", "wheel", "oldest-supported-numpy", "cython>=3", "raysect==0.7.1", "cherab==1.4"]
 build-backend="setuptools.build_meta"
```

**Comment by vsnever** [comment] 2024-07-09 11:56
Hello, @olivhoenen 
Thanks for this. I tested your patch on the RHEL9 SDCC login node and can confirm that after patching `pyproject.toml` `cherab-imas` installs and works fine.

**Comment by jacklovell** [comment] 2024-07-09 12:39
I remember when pinning Cython to the a5 release (done originally in cherab-solps, on which this package is based) that the a6 and a7 releases caused problems with Raysect's function framework. I believe I got 100% CPU hangs when calling `FunctionxD` objects. If that's been fixed by the released version of Cython 3.0 then it makes sense to remove the pin to a5.

**Comment by vsnever** [comment] 2024-07-09 13:15
> I remember when pinning Cython to the a5 release (done originally in cherab-solps, on which this package is based) that the a6 and a7 releases caused problems with Raysect's function framework. I believe I got 100% CPU hangs when calling FunctionxD objects. If that's been fixed by the released version of Cython 3.0 then it makes sense to remove the pin to a5.

The problem is that Raysect is not compatible with Cython >= 3.0, however, if a binary wheel is available (for Raysect 0.7.1 the Linux wheel is available for Python 3.7–3.12), Cherab compiles and works fine with Cython >= 3.0. Since Cython 3.0a5 doesn't support Python >= 3.10, I think we should move to Cython >= 3.0 in other packages as well.

**Comment by olivhoenen** [comment] 2024-07-09 18:13
By the way, we saw somewhere that cherab 1.5 was planned at least at some point, any news on that?

**Comment by vsnever** [comment] 2024-08-15 09:31
> By the way, we saw somewhere that cherab 1.5 was planned at least at some point, any news on that?

Cherab 1.5 RC1 is out. The final version will be released by the end of August. After that, within a week or so, we will update the add-ons to support version 1.5.

**Closed as completed** 2024-08-15 09:37 UTC
